// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common.proto
// Protobuf C++ Version: 6.33.2

#ifndef common_2eproto_2epb_2eh
#define common_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_common_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_common_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_common_2eproto;
}  // extern "C"
enum CmdProto : int;
extern const uint32_t CmdProto_internal_data_[];
enum RoomStatus : int;
extern const uint32_t RoomStatus_internal_data_[];
class User;
struct UserDefaultTypeInternal;
extern UserDefaultTypeInternal _User_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull User_class_data_;
class server_ping_req;
struct server_ping_reqDefaultTypeInternal;
extern server_ping_reqDefaultTypeInternal _server_ping_req_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull server_ping_req_class_data_;
class server_ping_resp;
struct server_ping_respDefaultTypeInternal;
extern server_ping_respDefaultTypeInternal _server_ping_resp_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull server_ping_resp_class_data_;
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::CmdProto_internal_data_>
    internal::EnumTraitsImpl::value<::CmdProto>;
template <>
internal::EnumTraitsT<::RoomStatus_internal_data_>
    internal::EnumTraitsImpl::value<::RoomStatus>;
}  // namespace protobuf
}  // namespace google

enum CmdProto : int {
  LOGIN = 0,
  PING = 1,
  LOGOUT = 2,
  SERVER_PING = 3,
  MATCH = 10,
  NEW_ROOM = 11,
  START_GAME = 12,
  END_GAME = 13,
  ROOM_UPDATE = 14,
  CHAT = 200,
  CmdProto_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  CmdProto_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t CmdProto_internal_data_[];
inline constexpr CmdProto CmdProto_MIN =
    static_cast<CmdProto>(0);
inline constexpr CmdProto CmdProto_MAX =
    static_cast<CmdProto>(200);
inline bool CmdProto_IsValid(int value) {
  return ::google::protobuf::internal::ValidateEnum(value, CmdProto_internal_data_);
}
inline constexpr int CmdProto_ARRAYSIZE = 200 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL CmdProto_descriptor();
template <typename T>
const ::std::string& CmdProto_Name(T value) {
  static_assert(::std::is_same<T, CmdProto>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to CmdProto_Name().");
  return ::google::protobuf::internal::NameOfEnum(CmdProto_descriptor(), value);
}
inline bool CmdProto_Parse(
    ::absl::string_view name, CmdProto* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<CmdProto>(CmdProto_descriptor(), name,
                                           value);
}
enum RoomStatus : int {
  INITED = 0,
  WAITTING = 1,
  READY = 2,
  STARTED = 3,
  GAMING = 4,
  ENDED = 5,
  SETTLED = 6,
  CLOSED = 7,
  CLEANED = 8,
  RoomStatus_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  RoomStatus_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t RoomStatus_internal_data_[];
inline constexpr RoomStatus RoomStatus_MIN =
    static_cast<RoomStatus>(0);
inline constexpr RoomStatus RoomStatus_MAX =
    static_cast<RoomStatus>(8);
inline bool RoomStatus_IsValid(int value) {
  return 0 <= value && value <= 8;
}
inline constexpr int RoomStatus_ARRAYSIZE = 8 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL RoomStatus_descriptor();
template <typename T>
const ::std::string& RoomStatus_Name(T value) {
  static_assert(::std::is_same<T, RoomStatus>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to RoomStatus_Name().");
  return RoomStatus_Name(static_cast<RoomStatus>(value));
}
template <>
inline const ::std::string& RoomStatus_Name(RoomStatus value) {
  return ::google::protobuf::internal::NameOfDenseEnum<RoomStatus_descriptor, 0, 8>(
      static_cast<int>(value));
}
inline bool RoomStatus_Parse(
    ::absl::string_view name, RoomStatus* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<RoomStatus>(RoomStatus_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class server_ping_resp final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:server_ping_resp) */ {
 public:
  inline server_ping_resp() : server_ping_resp(nullptr) {}
  ~server_ping_resp() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(server_ping_resp* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(server_ping_resp));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR server_ping_resp(::google::protobuf::internal::ConstantInitialized);

  inline server_ping_resp(const server_ping_resp& from) : server_ping_resp(nullptr, from) {}
  inline server_ping_resp(server_ping_resp&& from) noexcept
      : server_ping_resp(nullptr, ::std::move(from)) {}
  inline server_ping_resp& operator=(const server_ping_resp& from) {
    CopyFrom(from);
    return *this;
  }
  inline server_ping_resp& operator=(server_ping_resp&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const server_ping_resp& default_instance() {
    return *reinterpret_cast<const server_ping_resp*>(
        &_server_ping_resp_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(server_ping_resp& a, server_ping_resp& b) { a.Swap(&b); }
  inline void Swap(server_ping_resp* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(server_ping_resp* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  server_ping_resp* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<server_ping_resp>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const server_ping_resp& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const server_ping_resp& from) { server_ping_resp::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(server_ping_resp* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "server_ping_resp"; }

  explicit server_ping_resp(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  server_ping_resp(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const server_ping_resp& from);
  server_ping_resp(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, server_ping_resp&& from) noexcept
      : server_ping_resp(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTicketFieldNumber = 1,
  };
  // uint64 ticket = 1;
  void clear_ticket() ;
  ::uint64_t ticket() const;
  void set_ticket(::uint64_t value);

  private:
  ::uint64_t _internal_ticket() const;
  void _internal_set_ticket(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:server_ping_resp)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const server_ping_resp& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint64_t ticket_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_common_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull server_ping_resp_class_data_;
// -------------------------------------------------------------------

class server_ping_req final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:server_ping_req) */ {
 public:
  inline server_ping_req() : server_ping_req(nullptr) {}
  ~server_ping_req() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(server_ping_req* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(server_ping_req));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR server_ping_req(::google::protobuf::internal::ConstantInitialized);

  inline server_ping_req(const server_ping_req& from) : server_ping_req(nullptr, from) {}
  inline server_ping_req(server_ping_req&& from) noexcept
      : server_ping_req(nullptr, ::std::move(from)) {}
  inline server_ping_req& operator=(const server_ping_req& from) {
    CopyFrom(from);
    return *this;
  }
  inline server_ping_req& operator=(server_ping_req&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const server_ping_req& default_instance() {
    return *reinterpret_cast<const server_ping_req*>(
        &_server_ping_req_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(server_ping_req& a, server_ping_req& b) { a.Swap(&b); }
  inline void Swap(server_ping_req* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(server_ping_req* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  server_ping_req* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<server_ping_req>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const server_ping_req& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const server_ping_req& from) { server_ping_req::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(server_ping_req* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "server_ping_req"; }

  explicit server_ping_req(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  server_ping_req(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const server_ping_req& from);
  server_ping_req(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, server_ping_req&& from) noexcept
      : server_ping_req(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTicketFieldNumber = 1,
  };
  // uint64 ticket = 1;
  void clear_ticket() ;
  ::uint64_t ticket() const;
  void set_ticket(::uint64_t value);

  private:
  ::uint64_t _internal_ticket() const;
  void _internal_set_ticket(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:server_ping_req)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const server_ping_req& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint64_t ticket_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_common_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull server_ping_req_class_data_;
// -------------------------------------------------------------------

class User final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:User) */ {
 public:
  inline User() : User(nullptr) {}
  ~User() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(User* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(User));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR User(::google::protobuf::internal::ConstantInitialized);

  inline User(const User& from) : User(nullptr, from) {}
  inline User(User&& from) noexcept
      : User(nullptr, ::std::move(from)) {}
  inline User& operator=(const User& from) {
    CopyFrom(from);
    return *this;
  }
  inline User& operator=(User&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const User& default_instance() {
    return *reinterpret_cast<const User*>(
        &_User_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(User& a, User& b) { a.Swap(&b); }
  inline void Swap(User* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(User* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  User* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<User>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const User& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const User& from) { User::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(User* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "User"; }

  explicit User(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  User(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const User& from);
  User(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, User&& from) noexcept
      : User(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kAccountFieldNumber = 1,
    kNicknameFieldNumber = 2,
    kHeadimgFieldNumber = 3,
    kHeadframeFieldNumber = 7,
    kMobileFieldNumber = 8,
    kExpFieldNumber = 4,
    kLevelFieldNumber = 5,
    kIdFieldNumber = 6,
  };
  // string account = 1;
  void clear_account() ;
  const ::std::string& account() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_account(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_account();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_account();
  void set_allocated_account(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_account() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_account(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_account();

  public:
  // string nickname = 2;
  void clear_nickname() ;
  const ::std::string& nickname() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_nickname(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_nickname();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_nickname();
  void set_allocated_nickname(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_nickname() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_nickname(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_nickname();

  public:
  // string headimg = 3;
  void clear_headimg() ;
  const ::std::string& headimg() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_headimg(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_headimg();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_headimg();
  void set_allocated_headimg(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_headimg() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_headimg(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_headimg();

  public:
  // string headframe = 7;
  void clear_headframe() ;
  const ::std::string& headframe() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_headframe(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_headframe();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_headframe();
  void set_allocated_headframe(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_headframe() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_headframe(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_headframe();

  public:
  // string mobile = 8;
  void clear_mobile() ;
  const ::std::string& mobile() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_mobile(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_mobile();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_mobile();
  void set_allocated_mobile(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_mobile() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_mobile(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_mobile();

  public:
  // int32 exp = 4;
  void clear_exp() ;
  ::int32_t exp() const;
  void set_exp(::int32_t value);

  private:
  ::int32_t _internal_exp() const;
  void _internal_set_exp(::int32_t value);

  public:
  // int32 level = 5;
  void clear_level() ;
  ::int32_t level() const;
  void set_level(::int32_t value);

  private:
  ::int32_t _internal_level() const;
  void _internal_set_level(::int32_t value);

  public:
  // int32 id = 6;
  void clear_id() ;
  ::int32_t id() const;
  void set_id(::int32_t value);

  private:
  ::int32_t _internal_id() const;
  void _internal_set_id(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:User)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 8,
                                   0, 58,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const User& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr account_;
    ::google::protobuf::internal::ArenaStringPtr nickname_;
    ::google::protobuf::internal::ArenaStringPtr headimg_;
    ::google::protobuf::internal::ArenaStringPtr headframe_;
    ::google::protobuf::internal::ArenaStringPtr mobile_;
    ::int32_t exp_;
    ::int32_t level_;
    ::int32_t id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_common_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull User_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// User

// string account = 1;
inline void User::clear_account() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.account_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& User::account() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:User.account)
  return _internal_account();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void User::set_account(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.account_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:User.account)
}
inline ::std::string* PROTOBUF_NONNULL User::mutable_account()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_account();
  // @@protoc_insertion_point(field_mutable:User.account)
  return _s;
}
inline const ::std::string& User::_internal_account() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.account_.Get();
}
inline void User::_internal_set_account(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.account_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL User::_internal_mutable_account() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.account_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE User::release_account() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:User.account)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.account_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.account_.Set("", GetArena());
  }
  return released;
}
inline void User::set_allocated_account(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.account_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.account_.IsDefault()) {
    _impl_.account_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:User.account)
}

// string nickname = 2;
inline void User::clear_nickname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nickname_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& User::nickname() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:User.nickname)
  return _internal_nickname();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void User::set_nickname(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.nickname_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:User.nickname)
}
inline ::std::string* PROTOBUF_NONNULL User::mutable_nickname()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_nickname();
  // @@protoc_insertion_point(field_mutable:User.nickname)
  return _s;
}
inline const ::std::string& User::_internal_nickname() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.nickname_.Get();
}
inline void User::_internal_set_nickname(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nickname_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL User::_internal_mutable_nickname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.nickname_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE User::release_nickname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:User.nickname)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.nickname_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.nickname_.Set("", GetArena());
  }
  return released;
}
inline void User::set_allocated_nickname(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.nickname_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.nickname_.IsDefault()) {
    _impl_.nickname_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:User.nickname)
}

// string headimg = 3;
inline void User::clear_headimg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.headimg_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& User::headimg() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:User.headimg)
  return _internal_headimg();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void User::set_headimg(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.headimg_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:User.headimg)
}
inline ::std::string* PROTOBUF_NONNULL User::mutable_headimg()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_headimg();
  // @@protoc_insertion_point(field_mutable:User.headimg)
  return _s;
}
inline const ::std::string& User::_internal_headimg() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.headimg_.Get();
}
inline void User::_internal_set_headimg(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.headimg_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL User::_internal_mutable_headimg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.headimg_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE User::release_headimg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:User.headimg)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.headimg_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.headimg_.Set("", GetArena());
  }
  return released;
}
inline void User::set_allocated_headimg(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.headimg_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.headimg_.IsDefault()) {
    _impl_.headimg_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:User.headimg)
}

// int32 exp = 4;
inline void User::clear_exp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.exp_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline ::int32_t User::exp() const {
  // @@protoc_insertion_point(field_get:User.exp)
  return _internal_exp();
}
inline void User::set_exp(::int32_t value) {
  _internal_set_exp(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:User.exp)
}
inline ::int32_t User::_internal_exp() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.exp_;
}
inline void User::_internal_set_exp(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.exp_ = value;
}

// int32 level = 5;
inline void User::clear_level() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.level_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000040U);
}
inline ::int32_t User::level() const {
  // @@protoc_insertion_point(field_get:User.level)
  return _internal_level();
}
inline void User::set_level(::int32_t value) {
  _internal_set_level(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:User.level)
}
inline ::int32_t User::_internal_level() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.level_;
}
inline void User::_internal_set_level(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.level_ = value;
}

// int32 id = 6;
inline void User::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000080U);
}
inline ::int32_t User::id() const {
  // @@protoc_insertion_point(field_get:User.id)
  return _internal_id();
}
inline void User::set_id(::int32_t value) {
  _internal_set_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  // @@protoc_insertion_point(field_set:User.id)
}
inline ::int32_t User::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_;
}
inline void User::_internal_set_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = value;
}

// string headframe = 7;
inline void User::clear_headframe() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.headframe_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline const ::std::string& User::headframe() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:User.headframe)
  return _internal_headframe();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void User::set_headframe(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  _impl_.headframe_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:User.headframe)
}
inline ::std::string* PROTOBUF_NONNULL User::mutable_headframe()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::std::string* _s = _internal_mutable_headframe();
  // @@protoc_insertion_point(field_mutable:User.headframe)
  return _s;
}
inline const ::std::string& User::_internal_headframe() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.headframe_.Get();
}
inline void User::_internal_set_headframe(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.headframe_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL User::_internal_mutable_headframe() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.headframe_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE User::release_headframe() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:User.headframe)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000008U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  auto* released = _impl_.headframe_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.headframe_.Set("", GetArena());
  }
  return released;
}
inline void User::set_allocated_headframe(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }
  _impl_.headframe_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.headframe_.IsDefault()) {
    _impl_.headframe_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:User.headframe)
}

// string mobile = 8;
inline void User::clear_mobile() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.mobile_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline const ::std::string& User::mobile() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:User.mobile)
  return _internal_mobile();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void User::set_mobile(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  _impl_.mobile_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:User.mobile)
}
inline ::std::string* PROTOBUF_NONNULL User::mutable_mobile()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  ::std::string* _s = _internal_mutable_mobile();
  // @@protoc_insertion_point(field_mutable:User.mobile)
  return _s;
}
inline const ::std::string& User::_internal_mobile() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.mobile_.Get();
}
inline void User::_internal_set_mobile(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.mobile_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL User::_internal_mutable_mobile() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.mobile_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE User::release_mobile() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:User.mobile)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000010U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  auto* released = _impl_.mobile_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.mobile_.Set("", GetArena());
  }
  return released;
}
inline void User::set_allocated_mobile(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  }
  _impl_.mobile_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.mobile_.IsDefault()) {
    _impl_.mobile_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:User.mobile)
}

// -------------------------------------------------------------------

// server_ping_req

// uint64 ticket = 1;
inline void server_ping_req::clear_ticket() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ticket_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::uint64_t server_ping_req::ticket() const {
  // @@protoc_insertion_point(field_get:server_ping_req.ticket)
  return _internal_ticket();
}
inline void server_ping_req::set_ticket(::uint64_t value) {
  _internal_set_ticket(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:server_ping_req.ticket)
}
inline ::uint64_t server_ping_req::_internal_ticket() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ticket_;
}
inline void server_ping_req::_internal_set_ticket(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ticket_ = value;
}

// -------------------------------------------------------------------

// server_ping_resp

// uint64 ticket = 1;
inline void server_ping_resp::clear_ticket() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ticket_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::uint64_t server_ping_resp::ticket() const {
  // @@protoc_insertion_point(field_get:server_ping_resp.ticket)
  return _internal_ticket();
}
inline void server_ping_resp::set_ticket(::uint64_t value) {
  _internal_set_ticket(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:server_ping_resp.ticket)
}
inline ::uint64_t server_ping_resp::_internal_ticket() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ticket_;
}
inline void server_ping_resp::_internal_set_ticket(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ticket_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::CmdProto> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::CmdProto>() {
  return ::CmdProto_descriptor();
}
template <>
struct is_proto_enum<::RoomStatus> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::RoomStatus>() {
  return ::RoomStatus_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // common_2eproto_2epb_2eh
